/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DXC_Core.API
 * OpenAPI spec version: 1.0
 */
import type { ApiResultOfIconConfigDto, ApiResultOfListIconMobileDto } from '../models'

import { customRequest } from '../request'

export const getIconManagementMobile = () => {
  const getApiZaloMiniAppMobileServicesIconConfig = () => {
    return customRequest<ApiResultOfIconConfigDto>({
      url: `/api/zalo-mini-app/mobile/services/icon-config`,
      method: 'GET',
    })
  }
  const getApiZaloMiniAppMobileServicesIconsActive = () => {
    return customRequest<ApiResultOfListIconMobileDto>({
      url: `/api/zalo-mini-app/mobile/services/icons/active`,
      method: 'GET',
    })
  }
  return { getApiZaloMiniAppMobileServicesIconConfig, getApiZaloMiniAppMobileServicesIconsActive }
}
export type GetApiZaloMiniAppMobileServicesIconConfigResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementMobile>['getApiZaloMiniAppMobileServicesIconConfig']
    >
  >
>
export type GetApiZaloMiniAppMobileServicesIconsActiveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getIconManagementMobile>['getApiZaloMiniAppMobileServicesIconsActive']
    >
  >
>
